# Loads data from text files to a delta table.
# This load tests the following features:
#   - badrecordspath data validation.

dataflow:

  demo_landing:
    customer:
      type: Reader
      table:
        properties:
          yetl.metadata.timeslice: true
          yetl.schema.createIfNotExists: true

      path_date_format: "%Y%m%d"
      file_date_format: "%Y%m%d"
      format: csv
      path: landing/demo/{{timeslice_path_date_format}}/customer_{{timeslice_file_date_format}}.csv
      read:
        auto: true
        options:
          inferSchema: false
          header: true
          badRecordsPath: "exceptions/demo_landing/customer/{{timeslice_path_date_format}}"
      exceptions:
          path: "delta_lake/demo_landing/{{table_name}}_exceptions"
          database: demo_landing
          table: "{{table_name}}_exceptions"

      thresholds:
        warning:
          min_rows: 1
          max_rows: 1000
          exception_count: 0
          exception_percent: 0
        error:
          min_rows: 0
          max_rows: 100000000
          exception_count: 50
          exception_percent: 80
          
    customer_preferences:
      type: Reader
      table:
        properties:
          yetl.schema.createIfNotExists: true
          yetl.metadata.timeslice: false

      path_date_format: "%Y%m%d"
      file_date_format: "%Y%m%d"
      format: csv
      path: landing/demo/{{timeslice_path_date_format}}/customer_preferences_{{timeslice_file_date_format}}.csv
      read:
        options:
          inferSchema: false
          header: true
          badRecordsPath: "exceptions/demo_landing/customer_preferences/{{timeslice_path_date_format}}"
      exceptions:
          path: "delta_lake/demo_landing/{{table_name}}_exceptions"
          database: demo_landing
          table: "{{table_name}}_exceptions"
      thresholds:
        warning:
          min_rows: 0
          max_rows: 1000
          exception_count: 0
          exception_percent: 0
        error:
          min_rows: 0
          max_rows: 100000000
          exception_count: 50
          exception_percent: 80

  demo_raw:
    customer:
      type: DeltaWriter
      table:

        partitioned_by:
          - _partition_key

        zorder_by:
          - email
          - id

        ddl: "{{root}}"

        properties:

          yetl.metadata.dataset_id: true
          yetl.schema.createIfNotExists: true
          delta.appendOnly: false
          delta.checkpoint.writeStatsAsJson: true
          delta.autoOptimize.autoCompact: true        
          delta.autoOptimize.optimizeWrite: true 
          delta.compatibility.symlinkFormatManifest.enabled: false
          delta.dataSkippingNumIndexedCols: -1
          delta.logRetentionDuration: interval 30 days
          delta.deletedFileRetentionDuration: interval 1 week
          delta.enableChangeDataFeed: true
          delta.minReaderVersion: 1
          delta.minWriterVersion: 2
          delta.randomizeFilePrefixes: false
          delta.randomPrefixLength: 2

        check_constraints:
          amount_lower_bound: "amount > -1000"
          amount_upper_bound: "amount < 10000"
      
      format: delta
      path: delta_lake/demo_raw/customer
      write:
        mode: append
        options:
          mergeSchema: true
